# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning reali sample flask repo"
    type: "git-clone"
    repo: "https://github.com/reali-devops/python-app"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  Docker-Build:
    title: Building reali docker image
    type: "build"
    working_directory: '${{clone}}'
    dockerfile: "Dockerfile"
    image_name: 'einavl/reali-einav'
    tag: "1"
    stage: "build"



  sync_ebay-k8s-deployment:
    title: Sync ArgoCD reali app
    type: argocd-sync
    arguments:
      context: argocd
      app_name: reali



